[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lsmy-python-lib"
version = "1.0.0"
description = "Reusable Python library for LSMY systems"
readme = ""
requires-python = ">=3.8"